import { ProductCategory } from "@/lib/products";

export type SkinTypeLabel = "干皮" | "油皮" | "混油皮" | "敏感肌" | "痘痘肌";
export type UserGroupLabel =
  | "护肤新手"
  | "轻熟龄"
  | "屏障脆弱"
  | "容易长痘"
  | "容易出油"
  | "冬天易干";
export type ConcernLabel = "保湿" | "控油" | "修护" | "舒缓" | "提亮" | "防晒" | "减少闭口";
export type ExperienceLevelLabel = "beginner" | "intermediate" | "advanced";

export type SkincareKnowledgeProduct = {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  suitableSkinTypes: SkinTypeLabel[];
  suitableUserGroups: UserGroupLabel[];
  concerns: ConcernLabel[];
  experienceLevel: ExperienceLevelLabel;
  reason: string;
  caution: string;
  howToTry: string;
  tags: string[];
  sourceNote: string;
};

export const SKINCARE_KNOWLEDGE_PRODUCTS: SkincareKnowledgeProduct[] = [
  {
    id: "kp-cleanser-01",
    name: "示例氨基酸温和洁面",
    brand: "示例品牌",
    category: "cleanser",
    suitableSkinTypes: ["干皮", "混油皮", "敏感肌"],
    suitableUserGroups: ["护肤新手", "屏障脆弱", "冬天易干"],
    concerns: ["舒缓", "修护", "保湿"],
    experienceLevel: "beginner",
    reason: "清洁定位基础，适合希望减少过度清洁负担的人作为起步参考。",
    caution: "若你当前偏油且白天防晒叠加较多，晚间可能需要更充分的清洁搭配。",
    howToTry: "先从晚间单次清洁开始，连续观察 5-7 天是否有紧绷或不适。",
    tags: ["温和", "基础保湿", "新手友好"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-cleanser-02",
    name: "示例清爽平衡洁面",
    brand: "示例品牌",
    category: "cleanser",
    suitableSkinTypes: ["油皮", "混油皮", "痘痘肌"],
    suitableUserGroups: ["容易出油", "容易长痘", "护肤新手"],
    concerns: ["控油", "减少闭口"],
    experienceLevel: "beginner",
    reason: "偏向清爽清洁体验，适合出油明显且希望控制清洁后负担的人。",
    caution: "若你有明显敏感或泛红，建议避免高频清洁叠加。",
    howToTry: "先在晚间使用，每周 3-4 次，再根据肤感逐步调整频率。",
    tags: ["清爽", "控油", "新手友好"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-cleanser-03",
    name: "示例低刺激卸洁二合一",
    brand: "示例品牌",
    category: "cleanser",
    suitableSkinTypes: ["混油皮", "敏感肌"],
    suitableUserGroups: ["屏障脆弱", "护肤新手"],
    concerns: ["舒缓", "修护"],
    experienceLevel: "intermediate",
    reason: "适合想减少步骤复杂度、同时保持温和清洁节奏的人。",
    caution: "若你有高强度底妆场景，可能仍需分步清洁。",
    howToTry: "先在轻妆场景试用 1 周，观察是否出现残留或闷感。",
    tags: ["温和", "简化流程", "基础护理"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-toner-01",
    name: "示例舒缓保湿精华水",
    brand: "示例品牌",
    category: "toner-mist",
    suitableSkinTypes: ["干皮", "敏感肌", "混油皮"],
    suitableUserGroups: ["屏障脆弱", "护肤新手", "冬天易干"],
    concerns: ["保湿", "舒缓", "修护"],
    experienceLevel: "beginner",
    reason: "可作为基础补水与舒缓步骤参考，适合追求低风险叠加的人。",
    caution: "若你追求明显功效变化，单靠这一类产品通常不足。",
    howToTry: "先在洁面后单层使用，连续 1-2 周记录干燥与泛红变化。",
    tags: ["温和", "基础保湿", "新手友好"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-toner-02",
    name: "示例清爽控油化妆水",
    brand: "示例品牌",
    category: "toner-mist",
    suitableSkinTypes: ["油皮", "混油皮", "痘痘肌"],
    suitableUserGroups: ["容易出油", "容易长痘"],
    concerns: ["控油", "减少闭口"],
    experienceLevel: "intermediate",
    reason: "更适合希望在基础补水同时兼顾油脂管理的人群。",
    caution: "敏感阶段不建议与多种功效精华同期开启。",
    howToTry: "先在 T 区或局部试用，每周记录油光与闭口变化。",
    tags: ["清爽", "控油", "功效型"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-toner-03",
    name: "示例维稳喷雾",
    brand: "示例品牌",
    category: "toner-mist",
    suitableSkinTypes: ["敏感肌", "干皮", "混油皮"],
    suitableUserGroups: ["屏障脆弱", "冬天易干", "护肤新手"],
    concerns: ["舒缓", "修护"],
    experienceLevel: "beginner",
    reason: "适合作为状态不稳时的简化补充步骤，降低额外刺激概率。",
    caution: "若你已出现持续不适，需先减少变量再观察。",
    howToTry: "先在晚间少量使用 3-5 天，确认无不适后再加入日间。",
    tags: ["温和", "舒缓", "基础护理"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-serum-01",
    name: "示例基础修护精华",
    brand: "示例品牌",
    category: "serum",
    suitableSkinTypes: ["干皮", "敏感肌", "混油皮"],
    suitableUserGroups: ["屏障脆弱", "护肤新手", "轻熟龄"],
    concerns: ["修护", "舒缓", "保湿"],
    experienceLevel: "beginner",
    reason: "作为精华阶段的低风险参考，适合先建立耐受与连续记录。",
    caution: "若当前已叠加多款功效精华，建议避免同时新增。",
    howToTry: "先隔天晚间使用，连续 1-2 周观察稳定性后再决定频率。",
    tags: ["温和", "修护", "新手友好"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-serum-02",
    name: "示例清爽平衡精华",
    brand: "示例品牌",
    category: "serum",
    suitableSkinTypes: ["油皮", "混油皮", "痘痘肌"],
    suitableUserGroups: ["容易出油", "容易长痘"],
    concerns: ["控油", "减少闭口", "提亮"],
    experienceLevel: "intermediate",
    reason: "适合希望在控油与肤感平衡上做阶段性优化的人群。",
    caution: "若你近期有刺痛或泛红反馈，应优先回归基础护理。",
    howToTry: "先每周 2-3 次夜间单独使用，避免与其他强功效同晚叠加。",
    tags: ["清爽", "功效型", "分步尝试"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-serum-03",
    name: "示例进阶提亮精华",
    brand: "示例品牌",
    category: "serum",
    suitableSkinTypes: ["干皮", "混油皮"],
    suitableUserGroups: ["轻熟龄"],
    concerns: ["提亮", "修护"],
    experienceLevel: "advanced",
    reason: "更适合已有稳定基础流程、希望逐步提升目标护理的人。",
    caution: "新手或敏感期不建议直接高频加入。",
    howToTry: "先从低频晚间使用开始，至少观察 2 周再考虑加量。",
    tags: ["功效型", "进阶", "分步尝试"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-moisturizer-01",
    name: "示例清爽保湿乳液",
    brand: "示例品牌",
    category: "moisturizer",
    suitableSkinTypes: ["油皮", "混油皮", "痘痘肌"],
    suitableUserGroups: ["容易出油", "容易长痘", "护肤新手"],
    concerns: ["保湿", "控油", "舒缓"],
    experienceLevel: "beginner",
    reason: "适合作为基础保湿锚点，帮助减少只上功效产品的波动。",
    caution: "如果你处于冬季明显干燥期，可能需要更滋润质地。",
    howToTry: "先在晚间薄涂 1 周，观察是否出现油闷或干紧。",
    tags: ["清爽", "基础保湿", "新手友好"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-moisturizer-02",
    name: "示例屏障护理面霜",
    brand: "示例品牌",
    category: "moisturizer",
    suitableSkinTypes: ["干皮", "敏感肌", "混油皮"],
    suitableUserGroups: ["屏障脆弱", "冬天易干", "轻熟龄"],
    concerns: ["修护", "舒缓", "保湿"],
    experienceLevel: "beginner",
    reason: "适合在皮肤不稳或环境干燥阶段做基础支撑。",
    caution: "若你容易闷痘，建议先局部薄涂再决定全脸频率。",
    howToTry: "先在夜间重点干燥区试用 5-7 天，再调整到全脸。",
    tags: ["温和", "修护", "基础护理"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-moisturizer-03",
    name: "示例日间锁水乳霜",
    brand: "示例品牌",
    category: "moisturizer",
    suitableSkinTypes: ["干皮", "混油皮"],
    suitableUserGroups: ["冬天易干", "轻熟龄"],
    concerns: ["保湿", "修护"],
    experienceLevel: "intermediate",
    reason: "在白天流程中提供更稳定的保湿打底参考。",
    caution: "若与防晒叠加后出现搓泥，需调整用量与间隔。",
    howToTry: "先减少用量并拉开与防晒间隔，连续观察 1 周。",
    tags: ["基础保湿", "日间打底", "中阶"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-sunscreen-01",
    name: "示例日常轻薄防晒",
    brand: "示例品牌",
    category: "sunscreen",
    suitableSkinTypes: ["油皮", "混油皮", "敏感肌"],
    suitableUserGroups: ["护肤新手", "容易出油"],
    concerns: ["防晒", "舒缓"],
    experienceLevel: "beginner",
    reason: "适合作为日常通勤型防晒候选，强调可坚持的使用体验。",
    caution: "若你处于明显敏感期，需先进行局部耐受观察。",
    howToTry: "先在耳后或下颌线局部试用 2-3 天，再逐步扩展到全脸。",
    tags: ["清爽", "新手友好", "日常防晒"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-sunscreen-02",
    name: "示例保湿型防晒乳",
    brand: "示例品牌",
    category: "sunscreen",
    suitableSkinTypes: ["干皮", "敏感肌"],
    suitableUserGroups: ["冬天易干", "屏障脆弱", "护肤新手"],
    concerns: ["防晒", "保湿", "舒缓"],
    experienceLevel: "beginner",
    reason: "适合偏干或容易紧绷人群，在防晒步骤中兼顾基础保湿。",
    caution: "若你偏油，需注意用量避免白天负担感增加。",
    howToTry: "先在日间单次薄涂，记录 1 周的出油与舒适度变化。",
    tags: ["温和", "基础保湿", "防晒"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-sunscreen-03",
    name: "示例户外耐汗防晒",
    brand: "示例品牌",
    category: "sunscreen",
    suitableSkinTypes: ["混油皮", "油皮"],
    suitableUserGroups: ["容易出油"],
    concerns: ["防晒"],
    experienceLevel: "intermediate",
    reason: "用于高日晒场景的补充候选，强调场景化使用。",
    caution: "若你对成膜感敏感，日常室内场景可优先轻薄防晒。",
    howToTry: "先在户外活动日使用，观察闷感与补涂可接受度。",
    tags: ["防晒", "场景化", "中阶"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-mask-01",
    name: "示例舒缓急救面膜",
    brand: "示例品牌",
    category: "mask",
    suitableSkinTypes: ["干皮", "敏感肌", "混油皮"],
    suitableUserGroups: ["屏障脆弱", "冬天易干"],
    concerns: ["舒缓", "修护", "保湿"],
    experienceLevel: "beginner",
    reason: "适合作为状态波动期的临时补充，而非日常高频步骤。",
    caution: "不建议连续高频使用，避免造成额外负担。",
    howToTry: "先每周 1 次，观察次日肤感是否更稳定。",
    tags: ["温和", "急救护理", "基础护理"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-mask-02",
    name: "示例清洁平衡泥膜",
    brand: "示例品牌",
    category: "mask",
    suitableSkinTypes: ["油皮", "混油皮", "痘痘肌"],
    suitableUserGroups: ["容易出油", "容易长痘"],
    concerns: ["控油", "减少闭口"],
    experienceLevel: "intermediate",
    reason: "更适合油脂明显区域做阶段性清洁管理。",
    caution: "干皮或敏感阶段应减少频率并缩短停留时间。",
    howToTry: "先从局部使用开始，每周不超过 1 次并同步保湿观察。",
    tags: ["控油", "功效型", "分区护理"],
    sourceNote: "人工整理，后续需补充来源",
  },
  {
    id: "kp-mask-03",
    name: "示例夜间修护急救霜膜",
    brand: "示例品牌",
    category: "mask",
    suitableSkinTypes: ["干皮", "敏感肌"],
    suitableUserGroups: ["屏障脆弱", "冬天易干", "轻熟龄"],
    concerns: ["修护", "保湿", "舒缓"],
    experienceLevel: "beginner",
    reason: "在夜间流程中作为短期修护补充，适合干燥波动期。",
    caution: "若你容易闷痘，建议先少量分区使用。",
    howToTry: "先每周 1 次局部试用，确认稳定后再扩大范围。",
    tags: ["修护", "急救护理", "温和"],
    sourceNote: "人工整理，后续需补充来源",
  },
];
