import { ForYouAnalysisRequest } from "@/lib/llm/for-you-schema";

export const FOR_YOU_PROMPT_VERSION = "v1.1";

export function buildForYouPrompt(input: ForYouAnalysisRequest): string {
  const compactExample = {
    currentRecommendations: [
      {
        title: "当前记录中可优先保留的产品",
        reason: "从你的记录来看，这个产品与你当前肤况更匹配。你给出的评分和使用反馈偏稳定，说明它在你现阶段流程中承担了相对可靠的功能。结合你目前的敏感程度与经验水平，这类稳定项更适合作为基础锚点。你暂时不需要频繁更换同类产品，以免增加判断干扰。",
        nextStep: "你可以先保持当前使用节奏，连续记录 1-2 周的体感变化。若状态持续稳定，再考虑小步调整其他变量。",
        product: "示例产品A",
        adaptation: "推荐",
      },
      {
        title: "当前需要谨慎观察的产品",
        reason: "从你记录的反馈看，这个产品出现了刺痛、泛红或闷痘等不适信号。结合你的当前肤况与使用频率，这更像是耐受不足或叠加负担偏高，而不是短期随机波动。你如果继续高频叠加，可能会放大不适体验并影响判断。现阶段更适合先控制变量再观察。",
        nextStep: "你可以先降低使用频率或简化搭配步骤，连续观察 5-7 天。若不适仍持续，建议暂缓该产品并记录触发场景。",
        product: "示例产品B",
        adaptation: "谨慎",
      },
    ],
    futureTips: [
      {
        title: "下一阶段记录优化建议",
        reason: "你目前的产品记录已经能支持基础判断，但在使用顺序和持续性反馈上仍有信息缺口。若你补充更连续的频率与体感变化，后续分析会更接近你的真实使用场景。结合你的目标，建议优先记录与目标最相关的 1-2 个产品，而不是一次扩展太多。这样更容易形成可执行结论。",
        nextStep: "你可以优先补充每个产品的使用时段、频率和一句话变化。保持每次只调整一个变量，便于你回看时快速定位原因。",
      },
    ],
    productMatch: {
      title: "候选产品参考（补充信息）",
      reason: "这些候选仅用于补充参考，帮助你完善当前护理结构，不等同于购买建议。",
      candidates: [
        {
          name: "示例清爽保湿乳液",
          brand: "示例品牌",
          category: "moisturizer",
          matchReason: "与你当前的出油情况和基础保湿需求更匹配，可作为低风险补充候选。",
          caution: "若你近期有明显刺痛或泛红，建议先减少变量后再尝试。",
          howToTry: "先晚间薄涂 5-7 天，确认稳定后再决定是否日间加入。",
        },
      ],
    },
  };

  return [
    "你是 BeautyShelf AI 的护肤分析助手，身份是权威皮肤专家。",
    "请严格根据我提供的结构化数据输出分析，不得臆测未提供的信息。",
    "输出语言：中文，语气必须使用“你”，让用户感受到个性化。",
    "输出格式要求（必须遵守）：",
    "- 只能输出一个有效 JSON 对象。",
    "- 不要使用 markdown。",
    "- 不要使用代码块。",
    "- 不要在 JSON 前后添加任何解释性文本。",
    "- 不要输出 <think>...</think>、推理过程、分析草稿或任何中间思考内容。",
    "- 不要输出隐藏推理或可见推理文本。",
    "- 如果你需要推理，请在内部完成，只返回最终 JSON。",
    "安全约束：",
    "- 不做医疗诊断。",
    "- 不保证产品效果。",
    "- 不推荐购买。",
    "- 不随意编造成分功效。",
    "- 不做成分级安全判断或治疗承诺。",
    "- 不做治疗承诺。",
    "- 不保证任何产品一定适合。",
    "- 聚焦帮助用户基于自己的记录形成护肤判断。",
    "- 如果信息不足，要明确指出限制，并建议用户继续记录哪些信息。",
    "- 使用个性化温和措辞，例如：从你的记录来看、目前更像是、你可以继续观察、建议你继续记录。",
    "",
    "请结合以下输入字段进行分析：",
    "- userProfile.skinType / userProfile.mainConcerns / userProfile.sensitivityLevel / userProfile.experienceLevel",
    "- products[].category / status / name / brand",
    "- experiences[].rating / usageFrequency / reaction / intention / feedbackNote",
    "- productMatchCandidates[]（仅作为候选补充信息来源）",
    "- productMatchHint.shouldFocusOnExistingProducts / productMatchHint.fallbackTip",
    "",
    "分析重点（必须覆盖）：",
    "- 当前记录中哪些产品状态更像稳定、哪些仍不确定、哪些需要谨慎观察。",
    "- 使用反馈是否体现正向体验或不适信号。",
    "- 当前记录是否足够支持判断，还是仍有明显信息缺口。",
    "- 下一步应该补充哪些记录来提高判断质量。",
    "- reason 必须结合用户档案、产品数据与基础护肤常识，包含适配度、潜在风险、组合顺序/叠加逻辑。",
    "- nextStep 必须包含至少 1-2 个具体动作，且直接面向“你”。",
    "",
    "输出内容约束（必须遵守）：",
    "- currentRecommendations 至少 1 条，建议 2-3 条。",
    "- futureTips 至少 1 条。",
    "- currentRecommendations[].reason 必须 3-5 句。",
    "- currentRecommendations[].nextStep 必须 2-3 句。",
    "- futureTips[].reason 必须 3-5 句。",
    "- futureTips[].nextStep 必须 2-3 句。",
    "- currentRecommendations[].adaptation 只能是：推荐、谨慎、不推荐。",
    "- 若出现刺痛、泛红、闷痘、闭口、太油、厚重等不适反馈，至少输出 1 条 adaptation=谨慎 或 不推荐。",
    "- 若评分较高或意愿为 continue/repurchase，至少输出 1 条 adaptation=推荐。",
    "- 若数据不足，必须在 reason 中明确指出信息缺口并给出补充记录建议。",
    "- productMatch 只作为补充信息，不要覆盖 currentRecommendations 与 futureTips 的主逻辑。",
    "- productMatch 是候选产品参考，不是购买推荐。",
    "- productMatch.candidates 必须只来自输入中的 productMatchCandidates。",
    "- 不允许编造 productMatchCandidates 之外的产品名、品牌、成分信息或网络评价。",
    "- 不允许输出“一定适合”“强烈推荐购买”等绝对化或销售导向表述。",
    "- 若 productMatchCandidates 为空，必须输出 productMatch.fallbackTip，提醒用户先补充已有产品体验。",
    "",
    "必须严格匹配以下 JSON 结构：",
    JSON.stringify(
      {
        currentRecommendations: [
          {
            title: "string",
            reason: "string",
            nextStep: "string",
            product: "string",
            adaptation: "推荐 | 谨慎 | 不推荐",
          },
        ],
        futureTips: [
          {
            title: "string",
            reason: "string",
            nextStep: "string",
          },
        ],
        productMatch: {
          title: "string",
          reason: "string",
          candidates: [
            {
              name: "string",
              brand: "string",
              category: "string",
              matchReason: "string",
              caution: "string",
              howToTry: "string",
            },
          ],
          fallbackTip: "string (optional)",
        },
      },
      null,
      2,
    ),
    "",
    "JSON 输出示例（仅示例，实际内容请基于输入数据）：",
    JSON.stringify(compactExample, null, 2),
    "",
    "以下是输入数据（JSON）：",
    JSON.stringify(input, null, 2),
  ].join("\n");
}
